# Generated by Django 2.0.2 on 2018-02-07 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winyourhabit_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('proof_type', models.CharField(choices=[('text', 'text'), ('image', 'image')], default='text', max_length=10, verbose_name='ProofType')),
                ('start_date', models.DateTimeField()),
                ('time_frame', models.IntegerField(default=1)),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='prooftext',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image')], default='text', max_length=10, verbose_name='ProofType'),
        ),
    ]
