# Generated by Django 2.0.2 on 2018-02-08 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('winyourhabit_api', '0002_auto_20180208_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
