# Generated by Django 2.0.2 on 2018-02-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winyourhabit_api', '0003_auto_20180207_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitgroup',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
