# Generated by Django 2.0.2 on 2018-02-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winyourhabit_api', '0004_auto_20180207_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitgroup',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
