# Generated by Django 2.0.2 on 2018-02-07 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winyourhabit_api', '0006_auto_20180207_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitgroup',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
