# Generated by Django 2.0.2 on 2018-02-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winyourhabit_api', '0008_auto_20180207_2233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProofText',
            new_name='Proof',
        ),
    ]
