# Generated by Django 2.0.2 on 2018-02-08 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winyourhabit_api', '0009_auto_20180208_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegativeVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('start_date', models.DateTimeField()),
                ('valid', models.BooleanField(default=False)),
                ('bet_value', models.FloatField(default=1.0)),
                ('habit_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='winyourhabit_api.HabitGroup')),
                ('proof', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective', to='winyourhabit_api.Proof')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='negativevote',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negative_votes', to='winyourhabit_api.Objective'),
        ),
        migrations.AddField(
            model_name='negativevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negative_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
