# Generated by Django 2.0.2 on 2018-02-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winyourhabit_api', '0010_auto_20180208_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='proof',
        ),
        migrations.AddField(
            model_name='proof',
            name='objective',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='winyourhabit_api.Objective'),
        ),
    ]
