# Generated by Django 2.0.2 on 2018-02-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winyourhabit_api', '0011_auto_20180208_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
